### ISSUE TITLE
Consistentie

### ISSUE THREAD

**Issue by Tomvandenberg11** [Rellor/frontend-applications#10]
Probeer consistenter te zijn in je code! In sommige delen zie ik dat je gebruik maakt van de oude manier van `functions`, maar in andere delen zie ik dat je wel gebruik maakt van `Arrow functies`. 

Hetzelfde geldt voor het gebruik van `forEach` en `map`. Ik zie ze allebei voorbij komen, maar probeer hier consistenter in te zijn!

**Comment by Rellor** [comment]
Alles gelijk getrokken!
