### ISSUE TITLE
Styled Components

### ISSUE THREAD

**Issue by Tomvandenberg11** [Rellor/frontend-applications#2]
Probeer gebruik te maken van [Styled Components](https://styled-components.com/). Hierdoor kan je makkelijk je eigen style toevoegen, zonder dit in een apart CSS bestand te hoeven doen. 

Bijvoorbeeld: 
```javascript
const Title = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
`

return (
  <Title>Hello World!</Title>
)
```

**Comment by Rellor** [comment]
Ik maak momenteel alleen gebruik van een paar kleine globale css stukjes maar ga deze zeker onthouden! Bedankt
