### ISSUE TITLE
ES6 Arrow function

### ISSUE THREAD

**Issue by Tomvandenberg11** [Rellor/frontend-applications#3]
Probeer je functies om te bouwen naar [Arrow Functions.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions). Dit is een stuk netter en moderner dan de functies die jij gebruikt.

Bijvoorbeeld: 
```javascript
const Homebody = () => {
  /* Hier je code */
}
```

**Comment by Rellor** [comment]
Gedaan!
