### ISSUE TITLE
forEach

### ISSUE THREAD

**Issue by Tomvandenberg11** [Rellor/frontend-applications#5]
Probeer geen `forEach` functies meer te gebruiken, zoals hier:
https://github.com/Rellor/frontend-applications/blob/422bc55953addd3aabe4ca214838da375df4ce59/components/provider/Provider.jsx#L26-L36
Gebruik in plaats daarvan `map` of `filter`.

Dus in plaats van:
```
arr.forEach((num, index) => {
    return arr[index] = num * 2;
});
```

Gebruik:
```
let doubled = arr.map(num => {
    return num * 2;
});
```

Hierdoor is de code een stuk overzichtelijker en netter. Ook wordt de performance van je applicatie sneller. 
Zie ook [deze website](https://codeburst.io/javascript-map-vs-foreach-f38111822c0f).

**Comment by Rellor** [comment]
Foreach is weg!
